version: '3.7'
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        ports:
            - "5432:5432"

    vault:
        image: vault:latest
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root
            VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
        ports:
            - "8200:8200"
        depends_on:
            - postgres
